language: go
go:
  - "1.13"

os:
  - linux

services:
  - docker

# install:
#   - make image-build

# script:
#   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
#   - make push-image

deploy:
  - provider: script
    script: make image-build
    on:
      branch: master
  - provider: script
    script: make push-image
    on:
      branch: master