# 語言
language: go
# 版本
go:
  - "1.13"

os:
  - linux

# 會用到的服務
services:
  - docker

deploy:
  - provider: script
    script: make image-build
    on:
      branch: master
  - provider: script
    script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && \
            make push-image
    on:
      branch: master